name: Code quality check
run-name: Check code quality with linter
on: [ push ]
jobs:
    Detekt:
        runs-on: ubuntu-latest
        steps:
            -   name: set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 21

            -   uses: gradle/actions/setup-gradle@v3
                with:
                    cache-disabled: true

            -   name: Detekt
                shell: bash
                run: ./gradlew detekt
